Databases:

  MIAMI-CS: audio/code-switching/{uri}.wav
  # english: Miami-Corpus/audio/english/{uri}.wav
  # spanish: Miami-Corpus/audio/spanish/{uri}.wav

Protocols:

  MIAMI-CS:
    SpeakerDiarization:
      Overfitting:
          train:
            uri: lists/code-switch-train.txt
            annotation: reference/ref_{uri}.rttm
            annotated: uems/{uri}.uem

          development:
            uri: lists/code-switch-dev.txt
            annotation: reference/ref_{uri}.rttm
            annotated: uems/{uri}.uem
            
          test:
            uri: lists/code-switch-test.txt
            annotation: reference/ref_{uri}.rttm
            annotated: uems/{uri}.uem
